
/*
    Challenge 1.
    Write a SQL query that counts the number of films in each category in the Pagila database.
    - The query should return two columns: category and film_count
    - category should display the name of each category
    - film_count should show the total number of films in that category
    - Results should be grouped by category name
 */


-- your query here

select c.name, count(fc.film_id) from public.film_category fc 
inner join category c on c.category_id = fc.category_id 
group by c."name"


 /*
    Challenge 2.
    Write a SQL query that finds the top 5 customers who have spent the most money in the Pagila database.
    - The query should return three columns: first_name, last_name, and total_spent
    - total_spent should show the sum of all payments made by that customer
    - Results should be ordered by total_spent in descending order
    - The query should limit results to only the top 5 highest-spending customers
 */

 -- your query here

select c.first_name, c.last_name, sum(p.amount) as total_spent
from public.customer c 
inner join public.payment p on p.customer_id = c.customer_id 
group by (c.first_name, c.last_name)
order by total_spent desc
limit 5;


/*
    Challenge 3.
    Write a SQL query that lists all film titles that have been rented in the past 10 years in the Pagila database.
    - The query should return one column: title
    - title should display the name of each film that has been rented
    - The time period for "recent" should be within the last 10 years from the current date
    - Results should only include films that have rental records in this time period
*/


-- your query here

select f.title from public.film f
where exists (
select * from rental r
inner join inventory i on r.inventory_id  = i.inventory_id 
where f.film_id = i.film_id 
and r.rental_date >= CURRENT_DATE - INTERVAL '10 years'
)


/*
    Challenge 4.
    Write a SQL query that lists all films that have never been rented in the Pagila database.
    - The query should return two columns: title and inventory_id
    - title should display the name of each film that has never been rented
    - inventory_id should show the inventory ID of the specific copy
*/


-- your query here

select f.title, i.inventory_id from public.film f
inner join public.inventory i on i.film_id = f.film_id  
where not exists (
	select 1 from rental r 
	where i.inventory_id = r.inventory_id
)


/*
    Challenge 5.
    Write a SQL query that lists all films that were rented more times than the average rental count per film in the Pagila database.
    - The query should return two columns: title and rental_count
    - title should display the name of each film
    - rental_count should show the total number of times the film was rented
*/



-- your query here

select f.title, count(r.rental_id)
from public.film f 
inner join inventory i 
on i.film_id = f.film_id 
inner join rental r 
on r.inventory_id = i.inventory_id 
group by f.film_id , f.title
having count(r.rental_id) > (
	select avg(counts.cnt) 
	from (
		select count(rental_id) as cnt 
		from inventory i2 
		join rental r2 
		on r2.inventory_id = i2.inventory_id
		GROUP BY i2.film_id
	) counts 
);


/*
    Challenge 6.
    Write a SQL query that calculates rental activity for each customer.
    - The query should return the customer's first_name and last_name
    - It should also return their first rental date as first_rental
    - Their most recent rental date should be shown as last_rental
    - The difference in days between the first and last rentals should be shown as rental_span_days
    - Results should be grouped by customer and ordered by rental_span_days in descending order
*/

-- your query here

select c.first_name, c.last_name, 
min(r.rental_date) first_rental, 
max(r.rental_date) last_rental,
max(r.rental_date)::date - min(r.rental_date)::date as rental_span_days
from customer c 
inner join rental r on r.customer_id = c.customer_id
group by(c.customer_id, c.first_name, c.last_name)
order by rental_span_days desc;


/*
    Challenge 7.
    Find all customers who have not rented movies from every available genre.
    - The result should include the customer's first_name and last_name
    - Only include customers who are missing at least one genre in their rental history
*/


-- your query here

select c.first_name, c.last_name from customer c
left join rental r on c.customer_id = r.customer_id
left join inventory i on r.inventory_id = i.inventory_id
left join film_category fc on i.film_id = fc.film_id 
group by (c.customer_id, c.first_name, c.last_name)
having count(distinct(fc.category_id)) < (select count(*) from category)



/*
    Challenge 8.
    Create a materialized view that summarizes total rental revenue per film category.

    First, write a SQL query that returns the category name and the total revenue generated by rentals in that category.

    Use the following tables: payment, rental, inventory, film, film_category, and category.

    - Group the results by category name and order them by total revenue (descending).
    - Then, turn your query into a materialized view named revenue_by_category.
    - Query the materialized view to return:
    - All categories and their total revenue.
    - The top 3 categories by revenue.
    - Finally, refresh the materialized view manually using SQL.

    Once you finish the exercise, please answer the following questions: 
    
    When would you prefer a materialized view over a regular view? 
    
    When the query is very large because it has many joins or the tables have millions of rows, also because the user can't wait 
    so much time to get a result and having a delay of minutes or hours is acceptable.
    So, materialized view would be better for scenariso like Reports for Dashboards where is acceptable to have some delay

    How often should it be refreshed?

    It depends of much delay the objective of the materialized view can accept, it could be for minutes, hours o even a complete day,
    the time it takes to complete the query could be used as a reference and it could be done using an automatic process.
    Also it could be refreshed under some circunstances, maybe some company has a specific period of time where it receives a lot
    of insertions or updates to a table, so after it finishes could be a good moment to refresh the materializde view
    In the worst case, it could be refreshed each time the user required, knowing the it could take some time

*/

-- your work here

CREATE MATERIALIZED VIEW revenue_by_category AS
select c.name, sum(p.amount) total_revenue from category c
inner join film_category fc on fc.category_id = c.category_id 
inner join inventory i on i.film_id = fc.film_id 
inner join rental r on r.inventory_id = i.inventory_id 
inner join payment p on p.rental_id = r.rental_id 
group by c.category_id ,c.name
order by total_revenue desc;


SELECT * FROM revenue_by_category;

SELECT * FROM revenue_by_category limit 3;

REFRESH MATERIALIZED VIEW revenue_by_category;


